CREATE TABLE greet_info_python (
	"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 	"name" VARCHAR(30) NOT NULL, 
	"date" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE greet_info_go (
	"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 	"name" VARCHAR(30) NOT NULL, 
	"date" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE greeting (
	"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 	"greeting_str" VARCHAR(50) NOT NULL, 
	"date" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

CREATE TABLE history (
	"id" INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
 	"history_json" JSON NOT NULL, 
	"date" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);